# Generated by Django 4.1.7 on 2023-04-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_gender_alter_student_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
